# Generated by Django 6.0 on 2026-01-05 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_tarea_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={},
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('DIA', 'Corto plazo (día)'), ('ANIO', 'Largo plazo (año)')], default='DIA', max_length=4),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
